# action.yml
name: 'Publish apk to Sharepoint'
description: 'Create a archive of the repository and upload it to a Sharepoint library'
author: 'kqq'
branding:
  icon: 'upload-cloud'  
  color: 'green'
inputs:
  site_url: 
    description: 'The Sharepoint site url'
    required: true
  sharepoint_user: 
    description: 'User name to use for authentication'
    required: true
  sharepoint_password: 
    description: 'Password to use for authentication'
    required: true
  library_folder: 
    description: 'The path where to upload the archive in the library'
    required: true
    default: "Shared documents"
  apk_url:
    description: 'Apk Url'
    required: true
    default: "android/app/build/outputs/apk/release/app-release-signed.apk"
  apk_name:
    description: 'Apk Name'
    required: true
    default: "Sreading"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SITE_URL : ${{ inputs.site_url }}
    USER : ${{ inputs.sharepoint_user }}
    PASSWD: ${{ inputs.sharepoint_password }}
    LIB_FOLDER : ${{ inputs.library_folder }}
    APK_URL: ${{ inputs.apk_url }}
    APK_NAME: ${{ inputs.apk_name }}
